sonar.projectKey=nadaabdelhaliem999-hash_university-course-registration-system
sonar.organization=nadaabdelhaliem999-hash
sonar.projectName=University Course Registration System
sonar.projectVersion=1.0

sonar.sources=src,include
sonar.tests=tests


sonar.exclusions=**/tests/**,src/main.cpp

sonar.host.url=https://sonarcloud.io


sonar.coverageReportPaths=coverage.xml
