sonar.projectKey=nadaabdelhaliem999-hash_university-course-registration-system
sonar.organization=nadaabdelhaliem999-hash

sonar.sources=src,include
sonar.tests=tests

sonar.sourceEncoding=UTF-8

# DISABLE C/C++ ANALYSIS
sonar.c.file.suffixes=
sonar.cpp.file.suffixes=
sonar.objc.file.suffixes=
