sonar.projectKey=university-course-registration
sonar.projectName=University Course Registration System
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/*.pyc,tests/**
sonar.python.version=3.11
sonar.host.url=http://localhost:9000
sonar.token=sqp_1fe5c95aa9c9de7b43d78d876f8eab1f5ab74f2b
