name: CI Pipeline - C++

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y gcovr

      - name: Compile with coverage
        run: |
          g++ -std=c++17 -fprofile-arcs -ftest-coverage \
          src/*.cpp tests/test.cpp -Iinclude -o test_run

      - name: Run tests
        run: ./test_run

      - name: Generate coverage.xml
        run: |
          gcovr -r . --xml -o coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
